title: MOJ Form Builder Documentation

permalink: pretty

header_links:
  GitHub: https://github.com/ministryofjustice/fb-guide-and-runbook/

defaults:
  -
    scope:
      path: "guides"
    values:
      guide: true
  -
    scope:
      path: "hosting"
    values:
      hosting: true
